#include "Position.h"
#include "../bitboard/Bitboard.h"
#include <sstream>
#include <cctype>
#include <cstdlib>
#include <cmath>
namespace uc {
static bool own(int p,bool w){return w?p>0:p<0;} static bool opp(int p,bool w){return w?p<0:p>0;} static int ab(int p){return p<0?-p:p;}
Position::Position(){start();}
void Position::start(){setFEN("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1");}
int Position::parseSq(const std::string&s)const{if(s.size()!=2)return -1;int f=s[0]-'a',r=s[1]-'1';return(f<0||f>7||r<0||r>7)?-1:r*8+f;}
std::string Position::sqName(int s){return std::string{char('a'+(s&7)),char('1'+(s>>3))};}
bool Position::setFEN(const std::string&f){std::istringstream ss(f);std::string pl,turn,cas,ep,h,fu;if(!(ss>>pl>>turn>>cas>>ep>>h>>fu))return false;b_.fill(0);int sq=56;for(char c:pl){if(c=='/'){sq-=16;continue;}if(std::isdigit((unsigned char)c)){sq+=c-'0';continue;}int p=0;switch(c){case'P':p=WP;break;case'N':p=WN;break;case'B':p=WB;break;case'R':p=WR;break;case'Q':p=WQ;break;case'K':p=WK;break;case'p':p=BP;break;case'n':p=BN;break;case'b':p=BB;break;case'r':p=BR;break;case'q':p=BQ;break;case'k':p=BK;break;default:return false;}if(sq<0||sq>=64)return false;b_[sq++]=p;}side_=turn=="w"?1:-1;castling_=0;if(cas.find('K')!=std::string::npos)castling_|=1;if(cas.find('Q')!=std::string::npos)castling_|=2;if(cas.find('k')!=std::string::npos)castling_|=4;if(cas.find('q')!=std::string::npos)castling_|=8;ep_=ep=="-"?-1:parseSq(ep);if(ep!="-"&&ep_<0)return false;half_=std::stoi(h);full_=std::stoi(fu);hist_.clear();return true;}
std::string Position::fen()const{std::ostringstream o;for(int r=7;r>=0;r--){int e=0;for(int f=0;f<8;f++){int p=b_[r*8+f];if(!p){e++;continue;}if(e){o<<e;e=0;}char c=".PNBRQK"[ab(p)];if(p<0)c=char(std::tolower((unsigned char)c));o<<c;}if(e)o<<e;if(r)o<<'/';}o<<(side_==1?" w ":" b ");std::string c;if(castling_&1)c+='K';if(castling_&2)c+='Q';if(castling_&4)c+='k';if(castling_&8)c+='q';o<<(c.empty()?"-":c)<<' '<<(ep_<0?"-":sqName(ep_))<<' '<<half_<<' '<<full_;return o.str();}
bool Position::attacked(int s,bool w)const{auto bb=bitboards();return BitOps::attackersTo(s,bb,w)!=0;}
bool Position::inCheck(bool w)const{int k=w?WK:BK;for(int i=0;i<64;i++)if(b_[i]==k)return attacked(i,!w);return true;}
void Position::pawns(std::vector<Move>&m,int s,bool w)const{int r=s>>3,f=s&7,dr=w?1:-1,nr=r+dr,prom=w?7:0;if(nr<0||nr>7)return;int t=nr*8+f;if(!b_[t]){if(nr==prom){m.push_back({(uint8_t)s,(uint8_t)t,w?Flag::PromoKnight:Flag::PromoKnight});m.push_back({(uint8_t)s,(uint8_t)t,Flag::PromoBishop});m.push_back({(uint8_t)s,(uint8_t)t,Flag::PromoRook});m.push_back({(uint8_t)s,(uint8_t)t,Flag::PromoQueen});}else{m.push_back({(uint8_t)s,(uint8_t)t,Flag::Quiet});if((w&&r==1)||(!w&&r==6)){int t2=(w?r+2:r-2)*8+f;if(!b_[t2])m.push_back({(uint8_t)s,(uint8_t)t2,Flag::DoublePawn});}}}Bitboard caps=BitOps::pawn(s,w);while(caps){int c=BitOps::lsb(caps);caps&=caps-1;if(opp(b_[c],w)){if((c>>3)==prom){m.push_back({(uint8_t)s,(uint8_t)c,Flag::PromoKnightCapture});m.push_back({(uint8_t)s,(uint8_t)c,Flag::PromoBishopCapture});m.push_back({(uint8_t)s,(uint8_t)c,Flag::PromoRookCapture});m.push_back({(uint8_t)s,(uint8_t)c,Flag::PromoQueenCapture});}else m.push_back({(uint8_t)s,(uint8_t)c,Flag::Capture});}else if(c==ep_)m.push_back({(uint8_t)s,(uint8_t)c,Flag::EnPassant});}}
void Position::knights(std::vector<Move>&m,int s,bool w)const{Bitboard a=BitOps::knight(s);Bitboard ownMask=0;for(int i=0;i<64;i++)if(own(b_[i],w))ownMask|=1ULL<<i;a&=~ownMask;while(a){int t=BitOps::lsb(a);a&=a-1;m.push_back({(uint8_t)s,(uint8_t)t,b_[t]?Flag::Capture:Flag::Quiet});}}
void Position::sliders(std::vector<Move>&m,int s,bool w,const int[][2],int)const{auto bb=bitboards();Bitboard a=0;int p=ab(b_[s]);if(p==3)a=BitOps::bishop(s,bb.white|bb.black);else if(p==4)a=BitOps::rook(s,bb.white|bb.black);else a=BitOps::queen(s,bb.white|bb.black);Bitboard ownMask=w?bb.white:bb.black;a&=~ownMask;while(a){int t=BitOps::lsb(a);a&=a-1;m.push_back({(uint8_t)s,(uint8_t)t,b_[t]?Flag::Capture:Flag::Quiet});}}
void Position::king(std::vector<Move>&m,int s,bool w)const{Bitboard a=BitOps::king(s);Bitboard ownMask=w?bitboards().white:bitboards().black;a&=~ownMask;while(a){int t=BitOps::lsb(a);a&=a-1;m.push_back({(uint8_t)s,(uint8_t)t,b_[t]?Flag::Capture:Flag::Quiet});}if(w&&s==4&&!inCheck(true)){if((castling_&1)&&!b_[5]&&!b_[6]&&!attacked(5,false)&&!attacked(6,false))m.push_back({4,6,Flag::KingCastle});if((castling_&2)&&!b_[1]&&!b_[2]&&!b_[3]&&!attacked(3,false)&&!attacked(2,false))m.push_back({4,2,Flag::QueenCastle});}if(!w&&s==60&&!inCheck(false)){if((castling_&4)&&!b_[61]&&!b_[62]&&!attacked(61,true)&&!attacked(62,true))m.push_back({60,62,Flag::KingCastle});if((castling_&8)&&!b_[57]&&!b_[58]&&!b_[59]&&!attacked(59,true)&&!attacked(58,true))m.push_back({60,58,Flag::QueenCastle});}}
std::vector<Move> Position::pseudo()const{std::vector<Move>m;m.reserve(96);bool w=side_==1;for(int s=0;s<64;s++){int p=b_[s];if(!own(p,w))continue;switch(ab(p)){case 1:pawns(m,s,w);break;case 2:knights(m,s,w);break;case 3:sliders(m,s,w,nullptr,0);break;case 4:sliders(m,s,w,nullptr,0);break;case 5:sliders(m,s,w,nullptr,0);break;case 6:king(m,s,w);break;}}return m;}
std::vector<Move> Position::legal()const{std::vector<Move>o;auto ms=pseudo();o.reserve(ms.size());for(auto&m:ms){Position q=*this;if(q.make(m))o.push_back(m);}return o;}
bool Position::make(const Move&m){if(m.from>=64||m.to>=64||m.from==m.to)return false;int moving=b_[m.from];bool w=side_==1;if(ab(b_[m.to])==6)return false;if(!own(moving,w))return false;State st{m,b_[m.to],castling_,ep_,half_,full_};hist_.push_back(st);b_[m.from]=0;if(m.flag==Flag::EnPassant){int cs=m.to+(w?-8:8);st.captured=b_[cs];hist_.back().captured=st.captured;b_[cs]=0;}int placed=moving;if(isPromotion(m))placed=(w?1:-1)*promotionPiece(m);b_[m.to]=placed;if(m.flag==Flag::KingCastle){if(w){b_[5]=WR;b_[7]=0;}else{b_[61]=BR;b_[63]=0;}}else if(m.flag==Flag::QueenCastle){if(w){b_[3]=WR;b_[0]=0;}else{b_[59]=BR;b_[56]=0;}}if(ab(moving)==6){if(w)castling_&=~3;else castling_&=~12;}if(m.from==0||m.to==0)castling_&=~2;if(m.from==7||m.to==7)castling_&=~1;if(m.from==56||m.to==56)castling_&=~8;if(m.from==63||m.to==63)castling_&=~4;ep_=-1;if(ab(moving)==1&&std::abs(int(m.to)-int(m.from))==16)ep_=(m.from+m.to)/2;if(ab(moving)==1||st.captured)half_=0;else ++half_;if(!w)++full_;side_=-side_;if(inCheck(w)){undo();return false;}return true;}
void Position::undo(){if(hist_.empty())return;State st=hist_.back();hist_.pop_back();side_=-side_;bool w=side_==1;auto&m=st.move;b_[m.from]=b_[m.to];if(isPromotion(m))b_[m.from]=w?WP:BP;b_[m.to]=st.captured;if(m.flag==Flag::EnPassant){int cs=m.to+(w?-8:8);b_[m.to]=0;b_[cs]=st.captured;}if(m.flag==Flag::KingCastle){if(w){b_[7]=WR;b_[5]=0;}else{b_[63]=BR;b_[61]=0;}}else if(m.flag==Flag::QueenCastle){if(w){b_[0]=WR;b_[3]=0;}else{b_[56]=BR;b_[59]=0;}}castling_=st.castling;ep_=st.ep;half_=st.half;full_=st.full;}
void Position::makeNull(){State st{Move{},0,castling_,ep_,half_,full_};hist_.push_back(st);ep_=-1;++half_;if(side_==-1)++full_;side_=-side_;}
void Position::undoNull(){if(hist_.empty())return;State st=hist_.back();hist_.pop_back();castling_=st.castling;ep_=st.ep;half_=st.half;full_=st.full;side_=-side_;}
bool Position::over()const{return legal().empty();}
Bitboards Position::bitboards() const {Bitboards bb{};for(int sq=0;sq<64;sq++){int p=b_[sq];if(!p)continue;int t=std::abs(p)-1;int i=p>0?t:t+6;Bitboard bit=1ULL<<sq;bb.piece[i]|=bit;if(p>0)bb.white|=bit;else bb.black|=bit;}return bb;}
std::string Position::boardString()const{std::ostringstream o;for(int r=7;r>=0;r--){o<<r+1<<" ";for(int f=0;f<8;f++){int p=b_[r*8+f];o<<(p==0?'.':"PNBRQKpnbrqk"[p>0?p-1:5-p])<<' ';}o<<'\n';}o<<"  a b c d e f g h\n";return o.str();}
uint64_t perft(Position&p,int d){if(d==0)return 1;uint64_t n=0;for(auto&m:p.legal())if(p.make(m)){n+=perft(p,d-1);p.undo();}return n;}
}
